apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-logger-deployment
  labels:
    app: connection-logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connection-logger
  template:
    metadata:
      labels:
        app: connection-logger
    spec:
      containers:
      - name: connection-logger
        image: ermitavulpe/main:connection-logger-v1.1
        command: ["/bin/sh", "-c"]
        args: ["npm start | tee /logs/connection-logger.log"]
        ports:
        - containerPort: 3000
        - containerPort: 3306
        env:
        - name: SQL_HOST
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_SECRET_HOST
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_SECRET_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_SECRET_PASSWORD
        - name: SQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_SECRET_DATABASE
        volumeMounts:
        - name: log-volume
          mountPath: /logs
      volumes:
      - name: log-volume
        hostPath:
          path: /root/logs
---
apiVersion: v1
kind: Service
metadata:
  name: connection-logger-service
spec:
  selector:
    app: connection-logger
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: connection-logger-sql-connection-service
spec:
  selector:
    app: connection-logger
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  externalIPs:
    - 10.0.4.11